services:
  mongo:
    image: mongo:5.0
    container_name: nosql_db
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - tp2_appnet

  webapp:
    build:
      context: ./webapp-nodejs
    container_name: webapp-nodejs-tp2
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/webapp_db
    depends_on:
      - mongo
    networks:
      - tp2_appnet

  reverse-proxy-waf:
    image: owasp/modsecurity-crs:nginx
    container_name: waf_firewall
    restart: always
    ports:
      - "8080:8080"
    environment:
      - BACKEND=http://webapp:3000
      - SecRuleEngine=On
    depends_on:
      - webapp
    networks:
      - tp2_appnet
    volumes:
      - ./waf_logs:/var/log/nginx # logs do WAF

  elasticsearch:
    image: elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - tp2_appnet
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s http://localhost:9200/_cluster/health | grep -vq ''"status":"red"''',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  logstash:
    image: logstash:8.14.1
    container_name: logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./waf_logs:/var/log/waf:ro # monta logs para leitura
    ports:
      - "5000:5000" # porta padrão TCP (se precisar)
      - "12201:12201/udp" # porta GELF UDP, caso use
    networks:
      - tp2_appnet

  kibana:
    image: kibana:8.14.1
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - tp2_appnet

volumes:
  mongo_data:
  es_data:
  waf_logs:

networks:
  tp2_appnet:
    external: true
